# moodemoji/data.py
"""The mood vocabulary.

Two structures live here and nothing else:

``MOOD_CATEGORIES``
    Canonical moods grouped into families. Every mood has its own emoji --
    no emoji is reused across canonical moods.

``ALIASES``
    Synonyms pointing at a canonical mood. A term is either canonical or an
    alias, never both.

Adding a mood means adding one entry to the right category. Adding a synonym
means adding one entry to ``ALIASES``. The public API in ``core.py`` picks up
both automatically.
"""

MOOD_CATEGORIES = {
    # --- feeling good ------------------------------------------------------
    "positive": {
        "admiring": "👏",
        "aesthetic": "🖼️",
        "amused": "😆",
        "anticipating": "⏰",
        "awestruck": "🌟",
        "blissful": "😇",
        "charmed": "🥹",
        "cheerful": "😃",
        "confident": "💯",
        "content": "🙂",
        "courageous": "🦁",
        "craving": "🤤",
        "delighted": "😁",
        "empowered": "🦸",
        "entranced": "🌠",
        "euphoric": "🎆",
        "excited": "🤩",
        "festive": "🎉",
        "flattered": "🌺",
        "free": "🪁",
        "generous": "🎁",
        "giddy": "🤭",
        "grateful": "🙏",
        "happy": "😊",
        "hopeful": "🌱",
        "humble": "🙇",
        "inspired": "💡",
        "interested": "🔍",
        "joyful": "😄",
        "liberated": "🪽",
        "lucky": "🍀",
        "motivated": "🔥",
        "optimistic": "🌈",
        "proud": "🦚",
        "radiant": "✨",
        "relieved": "😮‍💨",
        "reverent": "📿",
        "romantic": "🌹",
        "safe": "🏠",
        "satisfied": "👌",
        "secure": "🔒",
        "spiritual": "🔮",
        "successful": "🥇",
        "thrilled": "🎢",
        "triumphant": "🏆",
        "validated": "✅",
        "vindicated": "⚔️",
        "wholesome": "🧸",
    },
    # --- feeling bad -------------------------------------------------------
    "negative": {
        "angry": "😠",
        "annoyed": "😤",
        "anxious": "😰",
        "ashamed": "🙈",
        "betrayed": "🗡️",
        "bitter": "🍋",
        "broke": "💸",
        "burdened": "🎒",
        "cheated": "🎲",
        "claustrophobic": "🧱",
        "contemptuous": "😒",
        "creeped out": "🕷️",
        "defeated": "🏳️",
        "depressed": "😔",
        "disappointed": "😞",
        "disgusted": "🤢",
        "disillusioned": "🪞",
        "disrespected": "👎",
        "distrustful": "🚨",
        "dreading": "🌘",
        "envious": "🫤",
        "forgotten": "📦",
        "fragile": "🥚",
        "frustrated": "😣",
        "furious": "🤬",
        "gloomy": "🌧️",
        "grieving": "🥀",
        "guilty": "😓",
        "hateful": "🖤",
        "heartbroken": "💔",
        "hopeless": "🕳️",
        "horrified": "😧",
        "ignored": "🔇",
        "insecure": "🫥",
        "invisible": "🫧",
        "irritated": "😖",
        "jealous": "🐍",
        "longing": "🌊",
        "miserable": "😩",
        "misunderstood": "🗯️",
        "neglected": "🍂",
        "numb": "🫠",
        "offended": "😑",
        "outraged": "💢",
        "overwhelmed": "😵",
        "panicked": "😳",
        "paranoid": "👁️",
        "pessimistic": "☁️",
        "petty": "🫵",
        "possessive": "🔐",
        "pressured": "🗜️",
        "regretful": "😥",
        "rejected": "🚫",
        "replaceable": "🔁",
        "resentful": "😾",
        "sad": "😢",
        "saudade": "🌅",
        "scared": "😨",
        "self loathing": "🕸️",
        "stormy": "🌩️",
        "stressed": "😫",
        "suffocated": "🫁",
        "terrified": "😱",
        "tormented": "⛓️",
        "trapped": "🪤",
        "traumatized": "💥",
        "unlucky": "🌚",
        "unworthy": "📉",
        "vengeful": "😡",
        "vulnerable": "🫗",
        "worried": "😟",
        "yearning": "🧲",
    },
    # --- how much gas is in the tank ---------------------------------------
    "energy": {
        "alert": "👀",
        "amped": "🔊",
        "burnt out": "🕯️",
        "crashing": "🛬",
        "drained": "🪫",
        "energized": "⚡",
        "exhausted": "😪",
        "groggy": "🥴",
        "hungover": "🍺",
        "hyper": "🚀",
        "jetlagged": "✈️",
        "lazy": "🦥",
        "napping": "🛏️",
        "overworked": "🏭",
        "recharging": "🔌",
        "refreshed": "🚿",
        "rested": "🛌",
        "restless": "🌀",
        "revved": "🏎️",
        "second wind": "🔄",
        "sleep deprived": "🌃",
        "sleepy": "💤",
        "sluggish": "🐌",
        "tired": "😴",
        "unstoppable": "🌋",
        "wide awake": "🌞",
        "winded": "💨",
        "wired": "☕",
        "zoned out": "📺",
    },
    # --- other people ------------------------------------------------------
    "social": {
        "affectionate": "😘",
        "apologetic": "🥲",
        "appreciated": "💐",
        "awkward": "😬",
        "belonging": "🧩",
        "compassionate": "🤲",
        "connected": "🔗",
        "crush": "💘",
        "desire": "💋",
        "devoted": "💍",
        "disconnected": "⛓️‍💥",
        "embarrassed": "😅",
        "empathetic": "💞",
        "estranged": "🚪",
        "flirty": "😉",
        "forgiven": "🙌",
        "forgiving": "🤍",
        "friendly": "🤝",
        "heard": "👂",
        "included": "🎟️",
        "infatuated": "💓",
        "introverted": "🐚",
        "lonely": "🥺",
        "love": "❤️",
        "loved": "🥰",
        "nurturing": "🍼",
        "outgoing": "🗣️",
        "pity": "😿",
        "popular": "📣",
        "protective": "🛡️",
        "respected": "🎖️",
        "shy": "🫣",
        "supported": "🫂",
        "sympathetic": "🫶",
        "trusting": "🤞",
        "unheard": "🔕",
        "welcoming": "👋",
    },
    # --- what the brain is doing -------------------------------------------
    "cognitive": {
        "amazed": "🤯",
        "analytical": "📊",
        "blocked": "⛔",
        "bored": "🥱",
        "brainstorming": "🧠",
        "calculating": "🧮",
        "certain": "☑️",
        "closed minded": "📕",
        "clueless": "🤷",
        "confused": "😕",
        "convinced": "✍️",
        "creative": "🎨",
        "curious": "🤔",
        "daydreaming": "🌤️",
        "decisive": "🔨",
        "determined": "💪",
        "distracted": "🦋",
        "enlightened": "🧘",
        "eureka": "🎇",
        "focused": "🎯",
        "forgetful": "🌫️",
        "in the zone": "🏄",
        "indecisive": "🤨",
        "judgmental": "🧑‍⚖️",
        "learning": "🎓",
        "logical": "➗",
        "meticulous": "📐",
        "naive": "🐣",
        "observant": "🔭",
        "open minded": "🌐",
        "overthinking": "🌪️",
        "philosophical": "🏛️",
        "planning": "🗺️",
        "poetic": "📜",
        "procrastinating": "🐢",
        "shocked": "😮",
        "skeptical": "🧐",
        "strategic": "♟️",
        "stuck": "🪨",
        "studious": "📚",
        "surprised": "😲",
        "thoughtful": "💭",
        "uncertain": "❓",
        "wise": "🦉",
    },
    # --- what the body is doing --------------------------------------------
    "physical": {
        "achy": "🤕",
        "allergic": "🤧",
        "bloated": "🎈",
        "breathless": "🌬️",
        "clean": "🧼",
        "clumsy": "🤸",
        "cold": "🥶",
        "congested": "😷",
        "dirty": "🪣",
        "dizzy": "😵‍💫",
        "drunk": "🍻",
        "feverish": "🌡️",
        "frozen": "🧊",
        "full": "😋",
        "graceful": "🩰",
        "hangry": "🍔",
        "healthy": "💚",
        "hot": "🥵",
        "hungry": "🍽️",
        "itchy": "🐜",
        "nauseous": "🤮",
        "overstimulated": "📳",
        "pampered": "💅",
        "recovering": "🩼",
        "sick": "🤒",
        "sober": "🚰",
        "sore": "🩹",
        "strong": "🦾",
        "sunburnt": "🔆",
        "sweaty": "💦",
        "thirsty": "🥤",
        "tingly": "✳️",
        "tipsy": "🥂",
        "weak": "🫨",
    },
    # --- being a menace ----------------------------------------------------
    "playful": {
        "adventurous": "🧗",
        "attention seeking": "📸",
        "boastful": "📢",
        "carefree": "🏖️",
        "chaotic": "🃏",
        "cheeky": "😜",
        "clever": "🔑",
        "competitive": "🥊",
        "cool": "😎",
        "dancing": "💃",
        "dramatic": "🎭",
        "gamer": "🎮",
        "goblin mode": "👺",
        "goofy": "🤡",
        "mischievous": "😈",
        "musical": "🎵",
        "nerdy": "🤓",
        "rebellious": "🤘",
        "rowdy": "🥁",
        "sarcastic": "🙃",
        "showing off": "🕺",
        "silly": "🤪",
        "silly goose": "🪿",
        "singing": "🎤",
        "smug": "😏",
        "spontaneous": "🪩",
        "sporty": "🏀",
        "teasing": "😝",
        "unhinged": "🎡",
        "whimsical": "🦄",
        "wild": "🤠",
        "witty": "✏️",
    },
    # --- level, in-between states ------------------------------------------
    "neutral": {
        "accepting": "🍵",
        "balanced": "⚖️",
        "blank": "😶",
        "busy": "🐝",
        "calm": "😌",
        "casual": "👕",
        "cautious": "🚧",
        "early": "🐓",
        "formal": "🎩",
        "indifferent": "🫰",
        "late": "🕐",
        "meh": "😐",
        "mellow": "🍃",
        "messy": "🧺",
        "nostalgic": "📻",
        "okay": "👍",
        "organized": "🗂️",
        "patient": "⏳",
        "peaceful": "☮️",
        "pensive": "🌙",
        "prepared": "🧭",
        "present": "🧿",
        "productive": "📈",
        "professional": "💼",
        "quiet": "🤫",
        "routine": "📅",
        "rushed": "🏃",
        "serene": "🕊️",
        "stoic": "🗿",
        "unprepared": "🎰",
    },
    # --- internet and modern shorthand -------------------------------------
    "slang": {
        "based": "🆒",
        "caught in 4k": "📹",
        "cooked": "🍳",
        "cringe": "🙊",
        "delulu": "🛸",
        "doomscrolling": "📱",
        "era": "🪐",
        "flexing": "💎",
        "fomo": "📲",
        "ghosted": "👻",
        "glow up": "⬆️",
        "goated": "🐐",
        "iykyk": "🤐",
        "jomo": "🏝️",
        "living rent free": "🏘️",
        "lowkey": "🔉",
        "main character": "🎬",
        "menty b": "📛",
        "npc": "🤖",
        "rizz": "😽",
        "salty": "🧂",
        "shook": "🫢",
        "slay": "👑",
        "soft launch": "🌸",
        "sus": "🕵️",
        "touch grass": "🌿",
        "vibing": "🎧",
        "washed": "🧽",
    },
    # --- the big questions -------------------------------------------------
    "existential": {
        "absurd": "🎪",
        "existential": "🌑",
        "impermanence": "⏱️",
        "insignificant": "🌌",
        "midlife crisis": "🏍️",
        "mortal": "💀",
        "nihilistic": "⚫",
        "oneness": "♾️",
        "pilgrim": "🥾",
        "purposeful": "⛰️",
        "questioning": "❔",
        "reborn": "🌄",
        "searching": "🔦",
        "solitude": "🏔️",
        "surrendered": "🧎",
        "transcendent": "🕉️",
    },
}

# Synonyms -> canonical mood. Values must exist in MOOD_CATEGORIES.
ALIASES = {
    # positive
    "admiration": "admiring",
    "impressed": "admiring",
    "in admiration": "admiring",
    "aesthetically pleased": "aesthetic",
    "moved by beauty": "aesthetic",
    "entertained": "amused",
    "tickled": "amused",
    "anticipation": "anticipating",
    "counting down": "anticipating",
    "expecting": "anticipating",
    "looking forward": "anticipating",
    "in awe": "awestruck",
    "wonderstruck": "awestruck",
    "heavenly": "blissful",
    "serene bliss": "blissful",
    "beguiled": "charmed",
    "enchanted": "charmed",
    "won over": "charmed",
    "bright": "cheerful",
    "chipper": "cheerful",
    "upbeat": "cheerful",
    "assured": "confident",
    "bold": "confident",
    "self assured": "confident",
    "at peace": "content",
    "comfortable": "content",
    "cosy": "content",
    "cozy": "content",
    "fulfilled": "content",
    "brave": "courageous",
    "fearless": "courageous",
    "gutsy": "courageous",
    "valiant": "courageous",
    "hankering": "craving",
    "hungry for": "craving",
    "chuffed": "delighted",
    "agency": "empowered",
    "capable": "empowered",
    "in control": "empowered",
    "captivated": "entranced",
    "mesmerized": "entranced",
    "spellbound": "entranced",
    "transfixed": "entranced",
    "elevated": "euphoric",
    "smitten with life": "euphoric",
    "cant wait": "excited",
    "champing at the bit": "excited",
    "eager": "excited",
    "enthusiastic": "excited",
    "hyped": "excited",
    "psyched": "excited",
    "pumped": "excited",
    "stoked": "excited",
    "celebratory": "festive",
    "party": "festive",
    "complimented": "flattered",
    "footloose": "free",
    "untethered": "free",
    "charitable": "generous",
    "giving": "generous",
    "openhanded": "generous",
    "giggly": "giddy",
    "appreciative": "grateful",
    "blessed": "grateful",
    "much obliged": "grateful",
    "thankful": "grateful",
    "buoyant": "happy",
    "dandy": "happy",
    "glad": "happy",
    "good": "happy",
    "grand": "happy",
    "great": "happy",
    "in a good mood": "happy",
    "peachy": "happy",
    "pleased": "happy",
    "sunny": "happy",
    "encouraged": "hopeful",
    "expectant": "hopeful",
    "fingers crossed": "hopeful",
    "modest": "humble",
    "unassuming": "humble",
    "creative spark": "inspired",
    "engaged": "interested",
    "interest": "interested",
    "keen": "interested",
    "elated": "joyful",
    "gleeful": "joyful",
    "jubilant": "joyful",
    "merry": "joyful",
    "overjoyed": "joyful",
    "unchained": "liberated",
    "unshackled": "liberated",
    "fortunate": "lucky",
    "ambitious": "motivated",
    "driven": "motivated",
    "fired up": "motivated",
    "focused fire": "motivated",
    "positive": "optimistic",
    "accomplished": "proud",
    "dignified": "proud",
    "pleased with myself": "proud",
    "beaming": "radiant",
    "glowing": "radiant",
    "reassured": "relieved",
    "unburdened": "relieved",
    "weight off my shoulders": "relieved",
    "devout": "reverent",
    "worshipful": "reverent",
    "amorous": "romantic",
    "lovey dovey": "romantic",
    "out of danger": "safe",
    "protected": "safe",
    "sheltered": "safe",
    "gratified": "satisfied",
    "on solid ground": "secure",
    "stable": "secure",
    "mystical": "spiritual",
    "soulful": "spiritual",
    "achieved": "successful",
    "winning big": "successful",
    "exhilarated": "thrilled",
    "victorious": "triumphant",
    "winning": "triumphant",
    "acknowledged": "validated",
    "affirmed": "validated",
    "justified": "vindicated",
    "proven right": "vindicated",
    "heartwarming": "wholesome",
    "sweet": "wholesome",
    # negative
    "cross": "angry",
    "heated": "angry",
    "hot under the collar": "angry",
    "mad": "angry",
    "riled": "angry",
    "steamed": "angry",
    "ticked off": "angry",
    "bothered": "annoyed",
    "miffed": "annoyed",
    "peeved": "annoyed",
    "apprehensive": "anxious",
    "jittery": "anxious",
    "nervous": "anxious",
    "on edge": "anxious",
    "stomach in knots": "anxious",
    "uneasy": "anxious",
    "worked up": "anxious",
    "humiliated": "ashamed",
    "mortified": "ashamed",
    "sheepish": "ashamed",
    "double crossed": "betrayed",
    "stabbed in the back": "betrayed",
    "cynical": "bitter",
    "jaded": "bitter",
    "sour": "bitter",
    "penniless": "broke",
    "skint": "broke",
    "strapped": "broke",
    "carrying a lot": "burdened",
    "weighed down": "burdened",
    "conned": "cheated",
    "ripped off": "cheated",
    "scammed": "cheated",
    "swindled": "cheated",
    "walls closing in": "claustrophobic",
    "contempt": "contemptuous",
    "disdainful": "contemptuous",
    "scornful": "contemptuous",
    "sneering": "contemptuous",
    "creeped": "creeped out",
    "skeeved": "creeped out",
    "unnerved": "creeped out",
    "beaten": "defeated",
    "demoralized": "defeated",
    "resigned": "defeated",
    "despondent": "depressed",
    "low": "depressed",
    "disheartened": "disappointed",
    "gutted": "disappointed",
    "let down": "disappointed",
    "grossed out": "disgusted",
    "repulsed": "disgusted",
    "revolted": "disgusted",
    "disenchanted": "disillusioned",
    "let down by life": "disillusioned",
    "belittled": "disrespected",
    "dismissed": "disrespected",
    "talked down to": "disrespected",
    "on guard": "distrustful",
    "wary of others": "distrustful",
    "dread": "dreading",
    "foreboding": "dreading",
    "impending doom": "dreading",
    "covetous": "envious",
    "left behind": "forgotten",
    "out of sight": "forgotten",
    "breakable": "fragile",
    "brittle": "fragile",
    "delicate": "fragile",
    "annoyed at everything": "frustrated",
    "exasperated": "frustrated",
    "fed up": "frustrated",
    "enraged": "furious",
    "irate": "furious",
    "livid": "furious",
    "seething": "furious",
    "dreary": "gloomy",
    "grey": "gloomy",
    "overcast": "gloomy",
    "bereaved": "grieving",
    "heartsore": "grieving",
    "mourning": "grieving",
    "remorseful": "guilty",
    "sorry": "guilty",
    "full of hate": "hateful",
    "loathing": "hateful",
    "broken hearted": "heartbroken",
    "crushed": "heartbroken",
    "hurt": "heartbroken",
    "lovesick": "heartbroken",
    "despairing": "hopeless",
    "helpless": "hopeless",
    "lost": "hopeless",
    "aghast": "horrified",
    "appalled": "horrified",
    "talked over": "ignored",
    "unacknowledged": "ignored",
    "inadequate": "insecure",
    "self conscious": "insecure",
    "unsure of myself": "insecure",
    "overlooked": "invisible",
    "unnoticed": "invisible",
    "agitated": "irritated",
    "cranky": "irritated",
    "grumpy": "irritated",
    "irked": "irritated",
    "aching for": "longing",
    "pining": "longing",
    "awful": "miserable",
    "terrible": "miserable",
    "wretched": "miserable",
    "not understood": "misunderstood",
    "taken the wrong way": "misunderstood",
    "unattended": "neglected",
    "uncared for": "neglected",
    "detached": "numb",
    "dissociated": "numb",
    "empty": "numb",
    "hollow": "numb",
    "affronted": "offended",
    "insulted": "offended",
    "indignant": "outraged",
    "scandalized": "outraged",
    "up in arms": "outraged",
    "buried": "overwhelmed",
    "flooded": "overwhelmed",
    "swamped": "overwhelmed",
    "too much going on": "overwhelmed",
    "alarmed": "panicked",
    "frantic": "panicked",
    "freaking out": "panicked",
    "conspiratorial": "paranoid",
    "paranoia": "paranoid",
    "watched": "paranoid",
    "downbeat": "pessimistic",
    "glass half empty": "pessimistic",
    "nitpicky": "petty",
    "small minded": "petty",
    "clingy": "possessive",
    "territorial": "possessive",
    "on the spot": "pressured",
    "squeezed": "pressured",
    "rueful": "regretful",
    "wistful": "regretful",
    "knocked back": "rejected",
    "spurned": "rejected",
    "turned down": "rejected",
    "expendable": "replaceable",
    "just a number": "replaceable",
    "begrudging": "resentful",
    "spiteful": "resentful",
    "blue": "sad",
    "crestfallen": "sad",
    "dejected": "sad",
    "down": "sad",
    "downcast": "sad",
    "forlorn": "sad",
    "glum": "sad",
    "heavy hearted": "sad",
    "melancholy": "sad",
    "sorrowful": "sad",
    "unhappy": "sad",
    "bittersweet": "saudade",
    "sweet sorrow": "saudade",
    "afraid": "scared",
    "fearful": "scared",
    "frightened": "scared",
    "quaking": "scared",
    "spooked": "scared",
    "self disgust": "self loathing",
    "self hatred": "self loathing",
    "tempestuous": "stormy",
    "turbulent": "stormy",
    "strained": "stressed",
    "tense": "stressed",
    "under pressure": "stressed",
    "cant breathe": "suffocated",
    "smothered": "suffocated",
    "horror struck": "terrified",
    "petrified": "terrified",
    "in torment": "tormented",
    "tortured": "tormented",
    "boxed in": "trapped",
    "cornered": "trapped",
    "no way out": "trapped",
    "scarred": "traumatized",
    "shell shocked": "traumatized",
    "cursed": "unlucky",
    "hard luck": "unlucky",
    "jinxed": "unlucky",
    "not good enough": "unworthy",
    "undeserving": "unworthy",
    "worthless": "unworthy",
    "out for revenge": "vengeful",
    "revengeful": "vengeful",
    "vindictive": "vengeful",
    "exposed": "vulnerable",
    "unguarded": "vulnerable",
    "wide open": "vulnerable",
    "concerned": "worried",
    "troubled": "worried",
    "craving deeply": "yearning",
    "hungering": "yearning",
    # energy
    "attentive": "alert",
    "awake": "alert",
    "sharp": "alert",
    "amped up": "amped",
    "juiced": "amped",
    "burned out": "burnt out",
    "burnout": "burnt out",
    "crispy": "burnt out",
    "fried": "burnt out",
    "coming down": "crashing",
    "energy crash": "crashing",
    "depleted": "drained",
    "running on empty": "drained",
    "charged": "energized",
    "lively": "energized",
    "peppy": "energized",
    "vigorous": "energized",
    "knackered": "exhausted",
    "shattered": "exhausted",
    "spent": "exhausted",
    "wiped": "exhausted",
    "foggy headed": "groggy",
    "just woke up": "groggy",
    "rough morning": "hungover",
    "the fear": "hungover",
    "bouncing": "hyper",
    "manic": "hyper",
    "jet lag": "jetlagged",
    "time zoned": "jetlagged",
    "idle": "lazy",
    "listless": "lazy",
    "unmotivated": "lazy",
    "having a lie down": "napping",
    "nap time": "napping",
    "grinding": "overworked",
    "worked to the bone": "overworked",
    "plugging in": "recharging",
    "topping up": "recharging",
    "rejuvenated": "refreshed",
    "renewed": "refreshed",
    "revitalized": "refreshed",
    "fresh": "rested",
    "restored": "rested",
    "antsy": "restless",
    "fidgety": "restless",
    "unsettled": "restless",
    "engine running": "revved",
    "revved up": "revved",
    "back at it": "second wind",
    "found my energy": "second wind",
    "no sleep": "sleep deprived",
    "running on fumes": "sleep deprived",
    "dozy": "sleepy",
    "drowsy": "sleepy",
    "heavy": "sluggish",
    "slow": "sluggish",
    "beat": "tired",
    "dead on my feet": "tired",
    "fatigued": "tired",
    "running low": "tired",
    "sleepy head": "tired",
    "weary": "tired",
    "worn out": "tired",
    "full send": "unstoppable",
    "on a roll": "unstoppable",
    "cant sleep": "wide awake",
    "eyes wide open": "wide awake",
    "out of breath": "winded",
    "puffed": "winded",
    "buzzing": "wired",
    "caffeinated": "wired",
    "checked out": "zoned out",
    "vacant stare": "zoned out",
    # social
    "cuddly": "affectionate",
    "tender": "affectionate",
    "warm": "affectionate",
    "contrite": "apologetic",
    "saying sorry": "apologetic",
    "seen": "appreciated",
    "valued": "appreciated",
    "cringey": "awkward",
    "out of place": "awkward",
    "uncomfortable": "awkward",
    "at home with them": "belonging",
    "part of something": "belonging",
    "compassion": "compassionate",
    "merciful": "compassionate",
    "tenderhearted": "compassionate",
    "in sync": "connected",
    "on the same wavelength": "connected",
    "butterflies": "crush",
    "crushing": "crush",
    "attracted": "desire",
    "wanting": "desire",
    "committed": "devoted",
    "loyal": "devoted",
    "drifted apart": "disconnected",
    "out of touch": "disconnected",
    "flustered": "embarrassed",
    "red faced": "embarrassed",
    "want the ground to swallow me": "embarrassed",
    "empathic": "empathetic",
    "empathy": "empathetic",
    "feeling with you": "empathetic",
    "cut off": "estranged",
    "no contact": "estranged",
    "coy": "flirty",
    "playful wink": "flirty",
    "absolved": "forgiven",
    "off the hook": "forgiven",
    "letting it go": "forgiving",
    "no hard feelings": "forgiving",
    "amiable": "friendly",
    "kind": "friendly",
    "sociable": "friendly",
    "listened to": "heard",
    "properly understood": "heard",
    "brought in": "included",
    "invited": "included",
    "head over heels": "infatuated",
    "obsessed with them": "infatuated",
    "inward": "introverted",
    "withdrawn": "introverted",
    "abandoned": "lonely",
    "alone": "lonely",
    "homesick": "lonely",
    "isolated": "lonely",
    "left out": "lonely",
    "no one around": "lonely",
    "on my own": "lonely",
    "adoring": "love",
    "besotted": "love",
    "in love": "love",
    "loving": "love",
    "smitten": "love",
    "adored": "loved",
    "cherished": "loved",
    "wanted": "loved",
    "caring for": "nurturing",
    "looking after": "nurturing",
    "chatty": "outgoing",
    "extroverted": "outgoing",
    "gregarious": "outgoing",
    "feel bad for them": "pity",
    "pitying": "pity",
    "everyones favourite": "popular",
    "in demand": "popular",
    "defensive": "protective",
    "guarded": "protective",
    "held in regard": "respected",
    "looked up to": "respected",
    "bashful": "shy",
    "reserved": "shy",
    "timid": "shy",
    "backed up": "supported",
    "cared for": "supported",
    "held": "supported",
    "commiserating": "sympathetic",
    "sympathy": "sympathetic",
    "hopeful in others": "trusting",
    "trustful": "trusting",
    "not listened to": "unheard",
    "talking to a wall": "unheard",
    "hospitable": "welcoming",
    # cognitive
    "astonished": "amazed",
    "dumbfounded": "amazed",
    "mind blown": "amazed",
    "analysing": "analytical",
    "breaking it down": "analytical",
    "creatively blocked": "blocked",
    "writers block": "blocked",
    "restive": "bored",
    "tedious": "bored",
    "twiddling my thumbs": "bored",
    "understimulated": "bored",
    "ideating": "brainstorming",
    "spitballing": "brainstorming",
    "running the numbers": "calculating",
    "scheming": "calculating",
    "no doubt": "certain",
    "sure": "certain",
    "not budging": "closed minded",
    "set in my ways": "closed minded",
    "bewildered": "clueless",
    "lost the plot": "clueless",
    "no idea": "clueless",
    "at sea": "confused",
    "baffled": "confused",
    "disoriented": "confused",
    "lost the thread": "confused",
    "muddled": "confused",
    "perplexed": "confused",
    "puzzled": "confused",
    "scratching my head": "confused",
    "persuaded": "convinced",
    "sold on it": "convinced",
    "artistic": "creative",
    "imaginative": "creative",
    "inventive": "creative",
    "inquisitive": "curious",
    "intrigued": "curious",
    "nosy": "curious",
    "want to know more": "curious",
    "wondering": "curious",
    "head in the clouds": "daydreaming",
    "off in a dream": "daydreaming",
    "made up my mind": "decisive",
    "resolved to act": "decisive",
    "not giving up": "determined",
    "persistent": "determined",
    "resolute": "determined",
    "stubborn": "determined",
    "tenacious": "determined",
    "scattered": "distracted",
    "spacey": "distracted",
    "unfocused": "distracted",
    "awakened": "enlightened",
    "centered": "enlightened",
    "mindful": "enlightened",
    "aha": "eureka",
    "it clicked": "eureka",
    "lightbulb moment": "eureka",
    "absorbed": "focused",
    "concentrated": "focused",
    "dialed in": "focused",
    "heads down": "focused",
    "locked in": "focused",
    "absent minded": "forgetful",
    "foggy": "forgetful",
    "flow": "in the zone",
    "flow state": "in the zone",
    "conflicted": "indecisive",
    "on the fence": "indecisive",
    "torn": "indecisive",
    "critical of everyone": "judgmental",
    "judging": "judgmental",
    "in training": "learning",
    "picking it up": "learning",
    "rational": "logical",
    "reasoned": "logical",
    "detail obsessed": "meticulous",
    "perfectionist": "meticulous",
    "precise": "meticulous",
    "green": "naive",
    "innocent": "naive",
    "wet behind the ears": "naive",
    "taking it in": "observant",
    "watching closely": "observant",
    "receptive": "open minded",
    "willing to hear it": "open minded",
    "in my head": "overthinking",
    "ruminating": "overthinking",
    "spiraling": "overthinking",
    "waxing philosophical": "philosophical",
    "mapping it out": "planning",
    "plotting": "planning",
    "lyrical": "poetic",
    "waxing poetic": "poetic",
    "avoiding it": "procrastinating",
    "putting it off": "procrastinating",
    "floored": "shocked",
    "speechless": "shocked",
    "stunned": "shocked",
    "doubtful": "skeptical",
    "suspicious": "skeptical",
    "unconvinced": "skeptical",
    "playing chess": "strategic",
    "thinking ahead": "strategic",
    "hit a wall": "stuck",
    "no progress": "stuck",
    "hitting the books": "studious",
    "swotting": "studious",
    "startled": "surprised",
    "taken aback": "surprised",
    "contemplative": "thoughtful",
    "musing": "thoughtful",
    "reflective": "thoughtful",
    "not sure": "uncertain",
    "unsure": "uncertain",
    "up in the air": "uncertain",
    "sage": "wise",
    "worldly": "wise",
    # physical
    "bruised": "achy",
    "hurting": "achy",
    "in pain": "achy",
    "allergies": "allergic",
    "sneezy": "allergic",
    "food baby": "bloated",
    "puffy": "bloated",
    "gasping": "breathless",
    "lungs burning": "breathless",
    "showered": "clean",
    "spotless": "clean",
    "butterfingers": "clumsy",
    "tripping over myself": "clumsy",
    "chilly": "cold",
    "freezing": "cold",
    "shivering": "cold",
    "blocked up": "congested",
    "stuffy nose": "congested",
    "grimy": "dirty",
    "grubby": "dirty",
    "need a shower": "dirty",
    "lightheaded": "dizzy",
    "woozy": "dizzy",
    "hammered": "drunk",
    "sloshed": "drunk",
    "wasted": "drunk",
    "burning up": "feverish",
    "running a temperature": "feverish",
    "icy": "frozen",
    "numb with cold": "frozen",
    "satiated": "full",
    "stuffed": "full",
    "elegant": "graceful",
    "poised": "graceful",
    "hungry and angry": "hangry",
    "need food now": "hangry",
    "fit": "healthy",
    "robust": "healthy",
    "well": "healthy",
    "boiling": "hot",
    "overheated": "hot",
    "sweltering": "hot",
    "could eat a horse": "hungry",
    "peckish": "hungry",
    "ravenous": "hungry",
    "starving": "hungry",
    "prickly": "itchy",
    "scratchy": "itchy",
    "queasy": "nauseous",
    "sick to my stomach": "nauseous",
    "sensory overload": "overstimulated",
    "too much input": "overstimulated",
    "spoiled": "pampered",
    "treated": "pampered",
    "healing": "recovering",
    "on the mend": "recovering",
    "ill": "sick",
    "poorly": "sick",
    "under the weather": "sick",
    "unwell": "sick",
    "clear headed": "sober",
    "not drinking": "sober",
    "stiff": "sore",
    "tender muscles": "sore",
    "mighty": "strong",
    "powerful": "strong",
    "burnt by the sun": "sunburnt",
    "lobster": "sunburnt",
    "clammy": "sweaty",
    "dehydrated": "thirsty",
    "parched": "thirsty",
    "buzzy skin": "tingly",
    "pins and needles": "tingly",
    "lightly drunk": "tipsy",
    "one too many": "tipsy",
    "feeble": "weak",
    "frail": "weak",
    "shaky": "weak",
    # playful
    "daring": "adventurous",
    "explorative": "adventurous",
    "intrepid": "adventurous",
    "look at me": "attention seeking",
    "main stage": "attention seeking",
    "big talk": "boastful",
    "bragging": "boastful",
    "breezy": "carefree",
    "without a care": "carefree",
    "chaos": "chaotic",
    "gremlin energy": "chaotic",
    "irreverent": "cheeky",
    "sassy": "cheeky",
    "saucy": "cheeky",
    "crafty": "clever",
    "smart": "clever",
    "in it to win it": "competitive",
    "must win": "competitive",
    "chill": "cool",
    "slick": "cool",
    "suave": "cool",
    "dancey": "dancing",
    "moving to it": "dancing",
    "extra": "dramatic",
    "over the top": "dramatic",
    "theatrical": "dramatic",
    "gaming": "gamer",
    "one more round": "gamer",
    "feral mode": "goblin mode",
    "goblin": "goblin mode",
    "clownish": "goofy",
    "ridiculous": "goofy",
    "devious": "mischievous",
    "impish": "mischievous",
    "naughty": "mischievous",
    "troublemaking": "mischievous",
    "humming along": "musical",
    "in the music": "musical",
    "bookish": "nerdy",
    "geeky": "nerdy",
    "contrary": "rebellious",
    "defiant": "rebellious",
    "punk": "rebellious",
    "boisterous": "rowdy",
    "raucous": "rowdy",
    "dry": "sarcastic",
    "ironic": "sarcastic",
    "snarky": "sarcastic",
    "wry": "sarcastic",
    "peacocking": "showing off",
    "performing": "showing off",
    "daft": "silly",
    "goofball": "silly",
    "in a silly mood": "silly",
    "zany": "silly",
    "absolute goose": "silly goose",
    "goose": "silly goose",
    "belting it out": "singing",
    "sing song": "singing",
    "cocky": "smug",
    "self satisfied": "smug",
    "no plan": "spontaneous",
    "on a whim": "spontaneous",
    "athletic": "sporty",
    "game on": "sporty",
    "joking": "teasing",
    "kidding": "teasing",
    "mocking": "teasing",
    "no thoughts": "unhinged",
    "off the rails": "unhinged",
    "fanciful": "whimsical",
    "twee": "whimsical",
    "feral": "wild",
    "reckless": "wild",
    "untamed": "wild",
    "quick witted": "witty",
    "sharp tongued": "witty",
    # neutral
    "at peace with it": "accepting",
    "come to terms": "accepting",
    "even keeled": "balanced",
    "grounded": "balanced",
    "steady": "balanced",
    "expressionless": "blank",
    "nothing": "blank",
    "vacant": "blank",
    "occupied": "busy",
    "slammed": "busy",
    "swamped with work": "busy",
    "composed": "calm",
    "cool as a cucumber": "calm",
    "relaxed": "calm",
    "settled": "calm",
    "tranquil": "calm",
    "unruffled": "calm",
    "dressed down": "casual",
    "relaxed dress": "casual",
    "careful": "cautious",
    "hesitant": "cautious",
    "wary": "cautious",
    "ahead of time": "early",
    "too early": "early",
    "black tie": "formal",
    "buttoned up": "formal",
    "apathetic": "indifferent",
    "unbothered": "indifferent",
    "uncaring": "indifferent",
    "behind schedule": "late",
    "running late": "late",
    "mid": "meh",
    "so so": "meh",
    "whatever": "meh",
    "easygoing": "mellow",
    "laid back": "mellow",
    "subdued": "mellow",
    "all over the place": "messy",
    "disorganized": "messy",
    "back in the day": "nostalgic",
    "homesick for the past": "nostalgic",
    "reminiscent": "nostalgic",
    "sentimental": "nostalgic",
    "alright": "okay",
    "decent": "okay",
    "fine": "okay",
    "in order": "organized",
    "sorted": "organized",
    "tidy": "organized",
    "enduring": "patient",
    "tolerant": "patient",
    "harmonious": "peaceful",
    "still": "peaceful",
    "brooding": "pensive",
    "moody": "pensive",
    "ready": "prepared",
    "set up": "prepared",
    "here now": "present",
    "in the moment": "present",
    "getting things done": "productive",
    "on a streak": "productive",
    "business mode": "professional",
    "work mode": "professional",
    "hushed": "quiet",
    "silent": "quiet",
    "on autopilot": "routine",
    "same as always": "routine",
    "in a hurry": "rushed",
    "no time": "rushed",
    "placid": "serene",
    "untroubled": "serene",
    "taking it on the chin": "stoic",
    "unmoved": "stoic",
    "not ready": "unprepared",
    "winging it": "unprepared",
    # slang
    "true to myself": "based",
    "unbothered by opinions": "based",
    "busted": "caught in 4k",
    "caught red handed": "caught in 4k",
    "done for": "cooked",
    "im cooked": "cooked",
    "cringing": "cringe",
    "second hand embarrassment": "cringe",
    "delusional": "delulu",
    "living a fantasy": "delulu",
    "doomscroll": "doomscrolling",
    "scrolling the void": "doomscrolling",
    "in my era": "era",
    "new chapter": "era",
    "flex": "flexing",
    "showing it off": "flexing",
    "fear of missing out": "fomo",
    "missing out": "fomo",
    "ghost": "ghosted",
    "left on read": "ghosted",
    "glowed up": "glow up",
    "transformation": "glow up",
    "goat": "goated",
    "greatest of all time": "goated",
    "if you know you know": "iykyk",
    "inside joke": "iykyk",
    "happily missing out": "jomo",
    "joy of missing out": "jomo",
    "cant stop thinking about it": "living rent free",
    "rent free": "living rent free",
    "low key": "lowkey",
    "quietly": "lowkey",
    "main character energy": "main character",
    "protagonist": "main character",
    "meltdown": "menty b",
    "mental breakdown": "menty b",
    "background character": "npc",
    "npc energy": "npc",
    "charisma": "rizz",
    "smooth talker": "rizz",
    "bitter about it": "salty",
    "sour grapes": "salty",
    "rattled": "shook",
    "shaken": "shook",
    "killing it": "slay",
    "slaying": "slay",
    "hinting at it": "soft launch",
    "soft launching": "soft launch",
    "something is off": "sus",
    "suspect": "sus",
    "need to go outside": "touch grass",
    "terminally online": "touch grass",
    "good vibes": "vibing",
    "in my element": "vibing",
    "vibe": "vibing",
    "over the hill": "washed",
    "past my prime": "washed",
    # existential
    "absurdist": "absurd",
    "cosmic joke": "absurd",
    "existential dread": "existential",
    "staring into the void": "existential",
    "nothing lasts": "impermanence",
    "this too shall pass": "impermanence",
    "a speck": "insignificant",
    "tiny in the universe": "insignificant",
    "crisis of meaning": "midlife crisis",
    "midlife": "midlife crisis",
    "aware of death": "mortal",
    "memento mori": "mortal",
    "nihilism": "nihilistic",
    "nothing matters": "nihilistic",
    "at one": "oneness",
    "connected to everything": "oneness",
    "on a journey": "pilgrim",
    "pilgrimage": "pilgrim",
    "on a mission": "purposeful",
    "sense of purpose": "purposeful",
    "questioning everything": "questioning",
    "why are we here": "questioning",
    "born again": "reborn",
    "fresh start": "reborn",
    "new beginning": "reborn",
    "looking for meaning": "searching",
    "seeking": "searching",
    "alone by choice": "solitude",
    "happy alone": "solitude",
    "letting go entirely": "surrendered",
    "surrender": "surrendered",
    "beyond myself": "transcendent",
    "transcendence": "transcendent",
}
