# moodemoji/data.py
"""The mood vocabulary.

Two structures live here and nothing else:

``MOOD_CATEGORIES``
    Canonical moods grouped into families. Every mood has its own emoji --
    no emoji is reused across canonical moods.

``ALIASES``
    Synonyms pointing at a canonical mood. A term is either canonical or an
    alias, never both.

Adding a mood means adding one entry to the right category. Adding a synonym
means adding one entry to ``ALIASES``. The public API in ``core.py`` picks up
both automatically.
"""

MOOD_CATEGORIES = {
    # --- feeling good -----------------------------------------------------
    "positive": {
        "happy": "😊",
        "excited": "🤩",
        "joyful": "😄",
        "cheerful": "😃",
        "delighted": "😁",
        "amused": "😆",
        "content": "🙂",
        "grateful": "🙏",
        "proud": "🦚",
        "optimistic": "🌈",
        "hopeful": "🌱",
        "blissful": "😇",
        "relieved": "😮‍💨",
        "satisfied": "👌",
        "euphoric": "🎆",
        "inspired": "💡",
        "motivated": "🔥",
        "confident": "💯",
        "lucky": "🍀",
        "festive": "🎉",
        "triumphant": "🏆",
        "radiant": "✨",
        "thrilled": "🎢",
        "giddy": "🤭",
        "awestruck": "🌟",
    },
    # --- feeling bad ------------------------------------------------------
    "negative": {
        "sad": "😢",
        "angry": "😠",
        "anxious": "😰",
        "depressed": "😔",
        "miserable": "😩",
        "frustrated": "😣",
        "disappointed": "😞",
        "scared": "😨",
        "terrified": "😱",
        "worried": "😟",
        "guilty": "😓",
        "ashamed": "🙈",
        "jealous": "🐍",
        "envious": "🫤",
        "regretful": "😥",
        "heartbroken": "💔",
        "grieving": "🥀",
        "hopeless": "🕳️",
        "bitter": "🍋",
        "resentful": "😾",
        "furious": "🤬",
        "annoyed": "😤",
        "irritated": "😖",
        "disgusted": "🤢",
        "horrified": "😧",
        "insecure": "🫥",
        "overwhelmed": "😵",
        "stressed": "😫",
        "panicked": "😳",
        "betrayed": "🗡️",
        "defeated": "🏳️",
        "numb": "🫠",
    },
    # --- how much gas is in the tank --------------------------------------
    "energy": {
        "tired": "😴",
        "energized": "⚡",
        "exhausted": "😪",
        "sleepy": "💤",
        "drained": "🪫",
        "refreshed": "🚿",
        "alert": "👀",
        "restless": "🌀",
        "lazy": "🦥",
        "wired": "☕",
        "sluggish": "🐌",
        "hyper": "🚀",
        "rested": "🛌",
        "burnt out": "🕯️",
    },
    # --- other people -----------------------------------------------------
    "social": {
        "love": "❤️",
        "loved": "🥰",
        "affectionate": "😘",
        "lonely": "🥺",
        "friendly": "🤝",
        "shy": "🫣",
        "flirty": "😉",
        "supported": "🫂",
        "welcoming": "👋",
        "awkward": "😬",
        "embarrassed": "😅",
        "trusting": "🤞",
        "appreciated": "💐",
        "outgoing": "🗣️",
        "introverted": "🐚",
        "protective": "🛡️",
    },
    # --- what the brain is doing ------------------------------------------
    "cognitive": {
        "confused": "😕",
        "curious": "🤔",
        "focused": "🎯",
        "thoughtful": "💭",
        "creative": "🎨",
        "determined": "💪",
        "distracted": "🦋",
        "bored": "🥱",
        "indecisive": "🤨",
        "skeptical": "🧐",
        "surprised": "😲",
        "shocked": "😮",
        "amazed": "🤯",
        "forgetful": "🌫️",
        "overthinking": "🌪️",
        "clueless": "🤷",
        "enlightened": "🧘",
    },
    # --- what the body is doing -------------------------------------------
    "physical": {
        "sick": "🤒",
        "hungry": "🍽️",
        "thirsty": "🥤",
        "full": "😋",
        "cold": "🥶",
        "hot": "🥵",
        "dizzy": "😵‍💫",
        "nauseous": "🤮",
        "achy": "🤕",
        "sweaty": "💦",
        "sore": "🩹",
        "healthy": "💚",
        "strong": "🦾",
        "weak": "🫨",
        "clean": "🧼",
    },
    # --- being a menace ---------------------------------------------------
    "playful": {
        "silly": "🤪",
        "mischievous": "😈",
        "goofy": "🤡",
        "sarcastic": "🙃",
        "cheeky": "😜",
        "teasing": "😝",
        "wild": "🤠",
        "adventurous": "🧗",
        "rebellious": "🤘",
        "smug": "😏",
        "nerdy": "🤓",
        "cool": "😎",
        "dramatic": "🎭",
    },
    # --- level --------------------------------------------------------------
    "neutral": {
        "calm": "😌",
        "meh": "😐",
        "okay": "👍",
        "blank": "😶",
        "indifferent": "🫰",
        "peaceful": "☮️",
        "serene": "🕊️",
        "balanced": "⚖️",
        "quiet": "🤫",
        "mellow": "🍃",
        "nostalgic": "📻",
        "pensive": "🌙",
        "patient": "⏳",
        "cautious": "🚧",
        "busy": "🐝",
    },
}

# Synonyms -> canonical mood. Values must exist in MOOD_CATEGORIES.
ALIASES = {
    # positive
    "glad": "happy",
    "pleased": "happy",
    "good": "happy",
    "great": "happy",
    "sunny": "happy",
    "upbeat": "cheerful",
    "bright": "cheerful",
    "chipper": "cheerful",
    "elated": "joyful",
    "overjoyed": "joyful",
    "jubilant": "joyful",
    "gleeful": "joyful",
    "merry": "joyful",
    "pumped": "excited",
    "stoked": "excited",
    "psyched": "excited",
    "eager": "excited",
    "enthusiastic": "excited",
    "hyped": "excited",
    "tickled": "amused",
    "entertained": "amused",
    "chuffed": "delighted",
    "thankful": "grateful",
    "appreciative": "grateful",
    "blessed": "grateful",
    "at peace": "content",
    "fulfilled": "content",
    "comfortable": "content",
    "cosy": "content",
    "cozy": "content",
    "accomplished": "proud",
    "dignified": "proud",
    "positive": "optimistic",
    "encouraged": "hopeful",
    "expectant": "hopeful",
    "heavenly": "blissful",
    "serene bliss": "blissful",
    "unburdened": "relieved",
    "reassured": "relieved",
    "gratified": "satisfied",
    "smitten with life": "euphoric",
    "elevated": "euphoric",
    "creative spark": "inspired",
    "driven": "motivated",
    "ambitious": "motivated",
    "focused fire": "motivated",
    "self assured": "confident",
    "assured": "confident",
    "bold": "confident",
    "fortunate": "lucky",
    "celebratory": "festive",
    "party": "festive",
    "victorious": "triumphant",
    "winning": "triumphant",
    "glowing": "radiant",
    "beaming": "radiant",
    "exhilarated": "thrilled",
    "giggly": "giddy",
    "in awe": "awestruck",
    "wonderstruck": "awestruck",
    # negative
    "unhappy": "sad",
    "down": "sad",
    "blue": "sad",
    "sorrowful": "sad",
    "glum": "sad",
    "melancholy": "sad",
    "mad": "angry",
    "cross": "angry",
    "heated": "angry",
    "nervous": "anxious",
    "uneasy": "anxious",
    "apprehensive": "anxious",
    "jittery": "anxious",
    "on edge": "anxious",
    "despondent": "depressed",
    "low": "depressed",
    "wretched": "miserable",
    "awful": "miserable",
    "terrible": "miserable",
    "annoyed at everything": "frustrated",
    "exasperated": "frustrated",
    "fed up": "frustrated",
    "let down": "disappointed",
    "disheartened": "disappointed",
    "afraid": "scared",
    "frightened": "scared",
    "fearful": "scared",
    "spooked": "scared",
    "petrified": "terrified",
    "horror struck": "terrified",
    "concerned": "worried",
    "troubled": "worried",
    "remorseful": "guilty",
    "sorry": "guilty",
    "humiliated": "ashamed",
    "mortified": "ashamed",
    "sheepish": "ashamed",
    "covetous": "envious",
    "rueful": "regretful",
    "wistful": "regretful",
    "broken hearted": "heartbroken",
    "hurt": "heartbroken",
    "crushed": "heartbroken",
    "lovesick": "heartbroken",
    "mourning": "grieving",
    "bereaved": "grieving",
    "despairing": "hopeless",
    "helpless": "hopeless",
    "lost": "hopeless",
    "jaded": "bitter",
    "cynical": "bitter",
    "sour": "bitter",
    "spiteful": "resentful",
    "begrudging": "resentful",
    "livid": "furious",
    "enraged": "furious",
    "seething": "furious",
    "irate": "furious",
    "peeved": "annoyed",
    "miffed": "annoyed",
    "bothered": "annoyed",
    "agitated": "irritated",
    "grumpy": "irritated",
    "cranky": "irritated",
    "irked": "irritated",
    "grossed out": "disgusted",
    "repulsed": "disgusted",
    "revolted": "disgusted",
    "appalled": "horrified",
    "aghast": "horrified",
    "self conscious": "insecure",
    "unsure of myself": "insecure",
    "inadequate": "insecure",
    "swamped": "overwhelmed",
    "buried": "overwhelmed",
    "flooded": "overwhelmed",
    "tense": "stressed",
    "strained": "stressed",
    "under pressure": "stressed",
    "frantic": "panicked",
    "freaking out": "panicked",
    "alarmed": "panicked",
    "stabbed in the back": "betrayed",
    "double crossed": "betrayed",
    "beaten": "defeated",
    "demoralized": "defeated",
    "resigned": "defeated",
    "empty": "numb",
    "hollow": "numb",
    "detached": "numb",
    "dissociated": "numb",
    # energy
    "sleepy head": "tired",
    "weary": "tired",
    "fatigued": "tired",
    "worn out": "tired",
    "beat": "tired",
    "knackered": "exhausted",
    "wiped": "exhausted",
    "spent": "exhausted",
    "shattered": "exhausted",
    "drowsy": "sleepy",
    "dozy": "sleepy",
    "depleted": "drained",
    "running on empty": "drained",
    "revitalized": "refreshed",
    "renewed": "refreshed",
    "rejuvenated": "refreshed",
    "charged": "energized",
    "lively": "energized",
    "peppy": "energized",
    "vigorous": "energized",
    "awake": "alert",
    "sharp": "alert",
    "attentive": "alert",
    "antsy": "restless",
    "fidgety": "restless",
    "unsettled": "restless",
    "idle": "lazy",
    "unmotivated": "lazy",
    "listless": "lazy",
    "caffeinated": "wired",
    "buzzing": "wired",
    "slow": "sluggish",
    "heavy": "sluggish",
    "bouncing": "hyper",
    "manic": "hyper",
    "restored": "rested",
    "fresh": "rested",
    "burned out": "burnt out",
    "burnout": "burnt out",
    "fried": "burnt out",
    "crispy": "burnt out",
    # social
    "in love": "love",
    "smitten": "love",
    "adoring": "love",
    "romantic": "love",
    "cherished": "loved",
    "adored": "loved",
    "wanted": "loved",
    "tender": "affectionate",
    "warm": "affectionate",
    "cuddly": "affectionate",
    "alone": "lonely",
    "isolated": "lonely",
    "abandoned": "lonely",
    "left out": "lonely",
    "homesick": "lonely",
    "sociable": "friendly",
    "amiable": "friendly",
    "kind": "friendly",
    "bashful": "shy",
    "timid": "shy",
    "reserved": "shy",
    "coy": "flirty",
    "playful wink": "flirty",
    "held": "supported",
    "backed up": "supported",
    "cared for": "supported",
    "hospitable": "welcoming",
    "cringey": "awkward",
    "uncomfortable": "awkward",
    "out of place": "awkward",
    "flustered": "embarrassed",
    "red faced": "embarrassed",
    "trustful": "trusting",
    "hopeful in others": "trusting",
    "valued": "appreciated",
    "seen": "appreciated",
    "extroverted": "outgoing",
    "chatty": "outgoing",
    "gregarious": "outgoing",
    "withdrawn": "introverted",
    "inward": "introverted",
    "defensive": "protective",
    "guarded": "protective",
    # cognitive
    "puzzled": "confused",
    "baffled": "confused",
    "perplexed": "confused",
    "muddled": "confused",
    "disoriented": "confused",
    "inquisitive": "curious",
    "wondering": "curious",
    "intrigued": "curious",
    "nosy": "curious",
    "locked in": "focused",
    "concentrated": "focused",
    "dialed in": "focused",
    "absorbed": "focused",
    "reflective": "thoughtful",
    "contemplative": "thoughtful",
    "musing": "thoughtful",
    "imaginative": "creative",
    "artistic": "creative",
    "inventive": "creative",
    "resolute": "determined",
    "persistent": "determined",
    "stubborn": "determined",
    "tenacious": "determined",
    "scattered": "distracted",
    "unfocused": "distracted",
    "spacey": "distracted",
    "restive": "bored",
    "understimulated": "bored",
    "tedious": "bored",
    "torn": "indecisive",
    "conflicted": "indecisive",
    "on the fence": "indecisive",
    "doubtful": "skeptical",
    "suspicious": "skeptical",
    "unconvinced": "skeptical",
    "startled": "surprised",
    "taken aback": "surprised",
    "stunned": "shocked",
    "floored": "shocked",
    "speechless": "shocked",
    "astonished": "amazed",
    "mind blown": "amazed",
    "dumbfounded": "amazed",
    "absent minded": "forgetful",
    "foggy": "forgetful",
    "ruminating": "overthinking",
    "spiraling": "overthinking",
    "in my head": "overthinking",
    "lost the plot": "clueless",
    "no idea": "clueless",
    "bewildered": "clueless",
    "mindful": "enlightened",
    "centered": "enlightened",
    "awakened": "enlightened",
    # physical
    "ill": "sick",
    "unwell": "sick",
    "poorly": "sick",
    "under the weather": "sick",
    "starving": "hungry",
    "peckish": "hungry",
    "ravenous": "hungry",
    "parched": "thirsty",
    "dehydrated": "thirsty",
    "stuffed": "full",
    "satiated": "full",
    "freezing": "cold",
    "chilly": "cold",
    "shivering": "cold",
    "sweltering": "hot",
    "boiling": "hot",
    "overheated": "hot",
    "lightheaded": "dizzy",
    "woozy": "dizzy",
    "queasy": "nauseous",
    "sick to my stomach": "nauseous",
    "in pain": "achy",
    "hurting": "achy",
    "bruised": "achy",
    "clammy": "sweaty",
    "stiff": "sore",
    "tender muscles": "sore",
    "well": "healthy",
    "fit": "healthy",
    "robust": "healthy",
    "powerful": "strong",
    "mighty": "strong",
    "feeble": "weak",
    "frail": "weak",
    "shaky": "weak",
    "spotless": "clean",
    "showered": "clean",
    # playful
    "goofball": "silly",
    "daft": "silly",
    "absurd": "silly",
    "zany": "silly",
    "impish": "mischievous",
    "devious": "mischievous",
    "naughty": "mischievous",
    "troublemaking": "mischievous",
    "clownish": "goofy",
    "ridiculous": "goofy",
    "snarky": "sarcastic",
    "wry": "sarcastic",
    "ironic": "sarcastic",
    "dry": "sarcastic",
    "saucy": "cheeky",
    "sassy": "cheeky",
    "irreverent": "cheeky",
    "mocking": "teasing",
    "joking": "teasing",
    "kidding": "teasing",
    "untamed": "wild",
    "feral": "wild",
    "reckless": "wild",
    "daring": "adventurous",
    "intrepid": "adventurous",
    "explorative": "adventurous",
    "defiant": "rebellious",
    "punk": "rebellious",
    "contrary": "rebellious",
    "self satisfied": "smug",
    "cocky": "smug",
    "geeky": "nerdy",
    "bookish": "nerdy",
    "chill": "cool",
    "suave": "cool",
    "slick": "cool",
    "theatrical": "dramatic",
    "extra": "dramatic",
    "over the top": "dramatic",
    # neutral
    "relaxed": "calm",
    "tranquil": "calm",
    "composed": "calm",
    "settled": "calm",
    "whatever": "meh",
    "so so": "meh",
    "mid": "meh",
    "fine": "okay",
    "alright": "okay",
    "decent": "okay",
    "expressionless": "blank",
    "vacant": "blank",
    "nothing": "blank",
    "apathetic": "indifferent",
    "unbothered": "indifferent",
    "uncaring": "indifferent",
    "still": "peaceful",
    "harmonious": "peaceful",
    "placid": "serene",
    "untroubled": "serene",
    "grounded": "balanced",
    "steady": "balanced",
    "even keeled": "balanced",
    "hushed": "quiet",
    "silent": "quiet",
    "subdued": "mellow",
    "easygoing": "mellow",
    "laid back": "mellow",
    "sentimental": "nostalgic",
    "reminiscent": "nostalgic",
    "homesick for the past": "nostalgic",
    "brooding": "pensive",
    "moody": "pensive",
    "tolerant": "patient",
    "enduring": "patient",
    "wary": "cautious",
    "careful": "cautious",
    "hesitant": "cautious",
    "swamped with work": "busy",
    "slammed": "busy",
    "occupied": "busy",
}
