name: Publish to TestPyPI

on:
  push:
    tags:
      - "v*.*.*-beta*"
      - "v*.*.*-rc*"
      - "v*.*.*-alpha*"

jobs:
  build-and-publish-testpypi:
    name: Build and publish to TestPyPI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install build dependencies
      run: pip install build twine

    - name: Build the package
      run: python -m build

    - name: Publish to TestPyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: twine upload --repository-url https://test.pypi.org/legacy/ dist/*
